/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ChapterType = { 'math' : null } |
  { 'science' : null };
export type ExternalBlob = Uint8Array;
export interface Flashcard {
  'id' : bigint,
  'front' : string,
  'exampleSentence' : string,
  'back' : string,
  'imageUrl' : [] | [string],
}
export interface Infographic {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'flowDiagram' : string,
  'interactiveElements' : Array<string>,
}
export type Language = { 'hindi' : null } |
  { 'hinglish' : null } |
  { 'english' : null };
export interface LogicExplanation {
  'id' : bigint,
  'concept' : string,
  'language' : Language,
  'whyInsights' : string,
  'stepByStepExplanation' : string,
}
export type OCRDocumentType = { 'assignment' : null } |
  { 'textbook' : null } |
  { 'worksheet' : null };
export interface OCRExtraction {
  '_id' : bigint,
  'documentType' : OCRDocumentType,
  '_percentage_textbook' : number,
  'content' : string,
  '_textbook_parts' : bigint,
  'validationResults' : string,
  'fileName' : string,
  '_total_text_parts' : bigint,
  'classId' : bigint,
  'schoolId' : bigint,
  'subjectId' : bigint,
  'relevance' : string,
  'pdfId' : [] | [ExternalBlob],
  'uploadTime' : Time,
  '_extracted_Questions' : string,
}
export interface Question {
  'correctAnswer' : string,
  'questionText' : string,
  'questionId' : bigint,
  'options' : Array<string>,
}
export interface School { 'name' : string, 'schoolId' : bigint }
export interface SlideDeck {
  'id' : bigint,
  'title' : string,
  'subject' : string,
  'slides' : Array<string>,
  'language' : Language,
  'summary' : string,
  'classLevel' : bigint,
}
export interface Student {
  'id' : bigint,
  'term2Marks' : bigint,
  'name' : string,
  'classId' : bigint,
  'schoolId' : bigint,
  'attendance' : bigint,
  'rollNumber' : string,
  'term1Marks' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'coinBalance' : bigint,
  'name' : string,
  'role' : string,
  'classId' : [] | [bigint],
  'schoolId' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisualNotebookChapter {
  'id' : bigint,
  'logicExplanations' : Array<LogicExplanation>,
  'title' : string,
  'subject' : string,
  'contentLanguage' : Language,
  'slideDeck' : SlideDeck,
  'extractionId' : bigint,
  'approvalStatus' : ApprovalStatus,
  'infographics' : Array<Infographic>,
  'creationTime' : Time,
  'classLevel' : bigint,
  'flashcards' : Array<Flashcard>,
  'uploadedBy' : string,
  'chapterType' : ChapterType,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClass' : ActorMethod<[string, bigint, bigint, number, number], undefined>,
  'addSchool' : ActorMethod<[bigint, string, number, number], undefined>,
  'addSchoolWithExactNameLookup' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteOCRData' : ActorMethod<[bigint], undefined>,
  'deleteVisualNotebookChapter' : ActorMethod<[bigint], undefined>,
  'getAcademicPerformance' : ActorMethod<
    [bigint, bigint],
    Array<[bigint, bigint]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChaptersByClassAndSubject' : ActorMethod<
    [bigint, string],
    Array<VisualNotebookChapter>
  >,
  'getCumulativeAverage' : ActorMethod<[bigint, bigint, bigint], bigint>,
  'getOCRExtractionByClass' : ActorMethod<[bigint], Array<OCRExtraction>>,
  'getOCRExtractionBySubject' : ActorMethod<[bigint], Array<OCRExtraction>>,
  'getOCRExtractionStats' : ActorMethod<[], bigint>,
  'getPublicDashboardData' : ActorMethod<
    [bigint, bigint],
    Array<[bigint, bigint]>
  >,
  'getQuestions' : ActorMethod<[bigint], [] | [Array<Question>]>,
  'getRandomQuestions' : ActorMethod<[bigint, bigint], [] | [Array<Question>]>,
  'getSchoolByExactName' : ActorMethod<[string], [] | [School]>,
  'getStudentData' : ActorMethod<[Principal], [] | [Student]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisualNotebookChapter' : ActorMethod<
    [bigint],
    [] | [VisualNotebookChapter]
  >,
  'getVisualNotebookChapters' : ActorMethod<[], Array<VisualNotebookChapter>>,
  'getVisualNotebookChaptersByExtractedId' : ActorMethod<
    [bigint],
    Array<VisualNotebookChapter>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerStudentWithSchoolName' : ActorMethod<
    [Student, Principal, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveOCRExtraction' : ActorMethod<[OCRExtraction], undefined>,
  'saveQuestions' : ActorMethod<[Question, bigint], undefined>,
  'saveVisualNotebookChapter' : ActorMethod<[VisualNotebookChapter], undefined>,
  'setVisualNotebookApprovalStatus' : ActorMethod<
    [bigint, ApprovalStatus],
    undefined
  >,
  'submitVisualNotebookChapter' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      Array<Flashcard>,
      SlideDeck,
      Array<Infographic>,
      Array<LogicExplanation>,
      string,
      Language,
      bigint,
      ChapterType,
      ApprovalStatus,
    ],
    bigint
  >,
  'updateUserCoinBalance' : ActorMethod<[Principal, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];