/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'coinBalance' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'classId' : IDL.Opt(IDL.Nat),
  'schoolId' : IDL.Opt(IDL.Nat),
});
export const Language = IDL.Variant({
  'hindi' : IDL.Null,
  'hinglish' : IDL.Null,
  'english' : IDL.Null,
});
export const LogicExplanation = IDL.Record({
  'id' : IDL.Nat,
  'concept' : IDL.Text,
  'language' : Language,
  'whyInsights' : IDL.Text,
  'stepByStepExplanation' : IDL.Text,
});
export const SlideDeck = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'slides' : IDL.Vec(IDL.Text),
  'language' : Language,
  'summary' : IDL.Text,
  'classLevel' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Infographic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'flowDiagram' : IDL.Text,
  'interactiveElements' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const Flashcard = IDL.Record({
  'id' : IDL.Nat,
  'front' : IDL.Text,
  'exampleSentence' : IDL.Text,
  'back' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const ChapterType = IDL.Variant({
  'math' : IDL.Null,
  'science' : IDL.Null,
});
export const VisualNotebookChapter = IDL.Record({
  'id' : IDL.Nat,
  'logicExplanations' : IDL.Vec(LogicExplanation),
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'contentLanguage' : Language,
  'slideDeck' : SlideDeck,
  'extractionId' : IDL.Nat,
  'approvalStatus' : ApprovalStatus,
  'infographics' : IDL.Vec(Infographic),
  'creationTime' : Time,
  'classLevel' : IDL.Nat,
  'flashcards' : IDL.Vec(Flashcard),
  'uploadedBy' : IDL.Text,
  'chapterType' : ChapterType,
});
export const OCRDocumentType = IDL.Variant({
  'assignment' : IDL.Null,
  'textbook' : IDL.Null,
  'worksheet' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const OCRExtraction = IDL.Record({
  '_id' : IDL.Nat,
  'documentType' : OCRDocumentType,
  '_percentage_textbook' : IDL.Float64,
  'content' : IDL.Text,
  '_textbook_parts' : IDL.Int,
  'validationResults' : IDL.Text,
  'fileName' : IDL.Text,
  '_total_text_parts' : IDL.Int,
  'classId' : IDL.Nat,
  'schoolId' : IDL.Nat,
  'subjectId' : IDL.Nat,
  'relevance' : IDL.Text,
  'pdfId' : IDL.Opt(ExternalBlob),
  'uploadTime' : Time,
  '_extracted_Questions' : IDL.Text,
});
export const Question = IDL.Record({
  'correctAnswer' : IDL.Text,
  'questionText' : IDL.Text,
  'questionId' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const School = IDL.Record({ 'name' : IDL.Text, 'schoolId' : IDL.Nat });
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'term2Marks' : IDL.Nat,
  'name' : IDL.Text,
  'classId' : IDL.Nat,
  'schoolId' : IDL.Nat,
  'attendance' : IDL.Nat,
  'rollNumber' : IDL.Text,
  'term1Marks' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClass' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'addSchool' : IDL.Func([IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64], [], []),
  'addSchoolWithExactNameLookup' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteOCRData' : IDL.Func([IDL.Nat], [], []),
  'deleteVisualNotebookChapter' : IDL.Func([IDL.Nat], [], []),
  'getAcademicPerformance' : IDL.Func(
      [IDL.Int, IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChaptersByClassAndSubject' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(VisualNotebookChapter)],
      ['query'],
    ),
  'getCumulativeAverage' : IDL.Func(
      [IDL.Int, IDL.Int, IDL.Nat],
      [IDL.Nat],
      ['query'],
    ),
  'getOCRExtractionByClass' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(OCRExtraction)],
      ['query'],
    ),
  'getOCRExtractionBySubject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(OCRExtraction)],
      ['query'],
    ),
  'getOCRExtractionStats' : IDL.Func([], [IDL.Nat], ['query']),
  'getPublicDashboardData' : IDL.Func(
      [IDL.Int, IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getQuestions' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Vec(Question))], ['query']),
  'getRandomQuestions' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Opt(IDL.Vec(Question))],
      [],
    ),
  'getSchoolByExactName' : IDL.Func([IDL.Text], [IDL.Opt(School)], ['query']),
  'getStudentData' : IDL.Func([IDL.Principal], [IDL.Opt(Student)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisualNotebookChapter' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(VisualNotebookChapter)],
      ['query'],
    ),
  'getVisualNotebookChapters' : IDL.Func(
      [],
      [IDL.Vec(VisualNotebookChapter)],
      ['query'],
    ),
  'getVisualNotebookChaptersByExtractedId' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(VisualNotebookChapter)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerStudentWithSchoolName' : IDL.Func(
      [Student, IDL.Principal, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveOCRExtraction' : IDL.Func([OCRExtraction], [], []),
  'saveQuestions' : IDL.Func([Question, IDL.Nat], [], []),
  'saveVisualNotebookChapter' : IDL.Func([VisualNotebookChapter], [], []),
  'setVisualNotebookApprovalStatus' : IDL.Func(
      [IDL.Nat, ApprovalStatus],
      [],
      [],
    ),
  'submitVisualNotebookChapter' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(Flashcard),
        SlideDeck,
        IDL.Vec(Infographic),
        IDL.Vec(LogicExplanation),
        IDL.Text,
        Language,
        IDL.Nat,
        ChapterType,
        ApprovalStatus,
      ],
      [IDL.Nat],
      [],
    ),
  'updateUserCoinBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'coinBalance' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'classId' : IDL.Opt(IDL.Nat),
    'schoolId' : IDL.Opt(IDL.Nat),
  });
  const Language = IDL.Variant({
    'hindi' : IDL.Null,
    'hinglish' : IDL.Null,
    'english' : IDL.Null,
  });
  const LogicExplanation = IDL.Record({
    'id' : IDL.Nat,
    'concept' : IDL.Text,
    'language' : Language,
    'whyInsights' : IDL.Text,
    'stepByStepExplanation' : IDL.Text,
  });
  const SlideDeck = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'slides' : IDL.Vec(IDL.Text),
    'language' : Language,
    'summary' : IDL.Text,
    'classLevel' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Infographic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'flowDiagram' : IDL.Text,
    'interactiveElements' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const Flashcard = IDL.Record({
    'id' : IDL.Nat,
    'front' : IDL.Text,
    'exampleSentence' : IDL.Text,
    'back' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const ChapterType = IDL.Variant({ 'math' : IDL.Null, 'science' : IDL.Null });
  const VisualNotebookChapter = IDL.Record({
    'id' : IDL.Nat,
    'logicExplanations' : IDL.Vec(LogicExplanation),
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'contentLanguage' : Language,
    'slideDeck' : SlideDeck,
    'extractionId' : IDL.Nat,
    'approvalStatus' : ApprovalStatus,
    'infographics' : IDL.Vec(Infographic),
    'creationTime' : Time,
    'classLevel' : IDL.Nat,
    'flashcards' : IDL.Vec(Flashcard),
    'uploadedBy' : IDL.Text,
    'chapterType' : ChapterType,
  });
  const OCRDocumentType = IDL.Variant({
    'assignment' : IDL.Null,
    'textbook' : IDL.Null,
    'worksheet' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const OCRExtraction = IDL.Record({
    '_id' : IDL.Nat,
    'documentType' : OCRDocumentType,
    '_percentage_textbook' : IDL.Float64,
    'content' : IDL.Text,
    '_textbook_parts' : IDL.Int,
    'validationResults' : IDL.Text,
    'fileName' : IDL.Text,
    '_total_text_parts' : IDL.Int,
    'classId' : IDL.Nat,
    'schoolId' : IDL.Nat,
    'subjectId' : IDL.Nat,
    'relevance' : IDL.Text,
    'pdfId' : IDL.Opt(ExternalBlob),
    'uploadTime' : Time,
    '_extracted_Questions' : IDL.Text,
  });
  const Question = IDL.Record({
    'correctAnswer' : IDL.Text,
    'questionText' : IDL.Text,
    'questionId' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const School = IDL.Record({ 'name' : IDL.Text, 'schoolId' : IDL.Nat });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'term2Marks' : IDL.Nat,
    'name' : IDL.Text,
    'classId' : IDL.Nat,
    'schoolId' : IDL.Nat,
    'attendance' : IDL.Nat,
    'rollNumber' : IDL.Text,
    'term1Marks' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClass' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'addSchool' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'addSchoolWithExactNameLookup' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteOCRData' : IDL.Func([IDL.Nat], [], []),
    'deleteVisualNotebookChapter' : IDL.Func([IDL.Nat], [], []),
    'getAcademicPerformance' : IDL.Func(
        [IDL.Int, IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChaptersByClassAndSubject' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(VisualNotebookChapter)],
        ['query'],
      ),
    'getCumulativeAverage' : IDL.Func(
        [IDL.Int, IDL.Int, IDL.Nat],
        [IDL.Nat],
        ['query'],
      ),
    'getOCRExtractionByClass' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(OCRExtraction)],
        ['query'],
      ),
    'getOCRExtractionBySubject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(OCRExtraction)],
        ['query'],
      ),
    'getOCRExtractionStats' : IDL.Func([], [IDL.Nat], ['query']),
    'getPublicDashboardData' : IDL.Func(
        [IDL.Int, IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getQuestions' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(Question))],
        ['query'],
      ),
    'getRandomQuestions' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Opt(IDL.Vec(Question))],
        [],
      ),
    'getSchoolByExactName' : IDL.Func([IDL.Text], [IDL.Opt(School)], ['query']),
    'getStudentData' : IDL.Func([IDL.Principal], [IDL.Opt(Student)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisualNotebookChapter' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(VisualNotebookChapter)],
        ['query'],
      ),
    'getVisualNotebookChapters' : IDL.Func(
        [],
        [IDL.Vec(VisualNotebookChapter)],
        ['query'],
      ),
    'getVisualNotebookChaptersByExtractedId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(VisualNotebookChapter)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerStudentWithSchoolName' : IDL.Func(
        [Student, IDL.Principal, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveOCRExtraction' : IDL.Func([OCRExtraction], [], []),
    'saveQuestions' : IDL.Func([Question, IDL.Nat], [], []),
    'saveVisualNotebookChapter' : IDL.Func([VisualNotebookChapter], [], []),
    'setVisualNotebookApprovalStatus' : IDL.Func(
        [IDL.Nat, ApprovalStatus],
        [],
        [],
      ),
    'submitVisualNotebookChapter' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(Flashcard),
          SlideDeck,
          IDL.Vec(Infographic),
          IDL.Vec(LogicExplanation),
          IDL.Text,
          Language,
          IDL.Nat,
          ChapterType,
          ApprovalStatus,
        ],
        [IDL.Nat],
        [],
      ),
    'updateUserCoinBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };