/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SlideDeck {
    id: bigint;
    title: string;
    subject: string;
    slides: Array<string>;
    language: Language;
    summary: string;
    classLevel: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface LogicExplanation {
    id: bigint;
    concept: string;
    language: Language;
    whyInsights: string;
    stepByStepExplanation: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface VisualNotebookChapter {
    id: bigint;
    logicExplanations: Array<LogicExplanation>;
    title: string;
    subject: string;
    contentLanguage: Language;
    slideDeck: SlideDeck;
    extractionId: bigint;
    approvalStatus: ApprovalStatus;
    infographics: Array<Infographic>;
    creationTime: Time;
    classLevel: bigint;
    flashcards: Array<Flashcard>;
    uploadedBy: string;
    chapterType: ChapterType;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Infographic {
    id: bigint;
    title: string;
    description: string;
    flowDiagram: string;
    interactiveElements: Array<string>;
}
export interface Flashcard {
    id: bigint;
    front: string;
    exampleSentence: string;
    back: string;
    imageUrl?: string;
}
export interface School {
    name: string;
    schoolId: bigint;
}
export interface Question {
    correctAnswer: string;
    questionText: string;
    questionId: bigint;
    options: Array<string>;
}
export interface OCRExtraction {
    _id: bigint;
    documentType: OCRDocumentType;
    _percentage_textbook: number;
    content: string;
    _textbook_parts: bigint;
    validationResults: string;
    fileName: string;
    _total_text_parts: bigint;
    classId: bigint;
    schoolId: bigint;
    subjectId: bigint;
    relevance: string;
    pdfId?: ExternalBlob;
    uploadTime: Time;
    _extracted_Questions: string;
}
export interface UserProfile {
    coinBalance: bigint;
    name: string;
    role: string;
    classId?: bigint;
    schoolId?: bigint;
}
export interface Student {
    id: bigint;
    term2Marks: bigint;
    name: string;
    classId: bigint;
    schoolId: bigint;
    attendance: bigint;
    rollNumber: string;
    term1Marks: bigint;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ChapterType {
    math = "math",
    science = "science"
}
export enum Language {
    hindi = "hindi",
    hinglish = "hinglish",
    english = "english"
}
export enum OCRDocumentType {
    assignment = "assignment",
    textbook = "textbook",
    worksheet = "worksheet"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addClass(name: string, classId: bigint, schoolId: bigint, latitude: number, longitude: number): Promise<void>;
    addSchool(schoolId: bigint, name: string, latitude: number, longitude: number): Promise<void>;
    addSchoolWithExactNameLookup(schoolId: bigint, name: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteOCRData(docId: bigint): Promise<void>;
    deleteVisualNotebookChapter(chapterId: bigint): Promise<void>;
    getAcademicPerformance(year: bigint, classId: bigint): Promise<Array<[bigint, bigint]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChaptersByClassAndSubject(classLevel: bigint, subject: string): Promise<Array<VisualNotebookChapter>>;
    getCumulativeAverage(year: bigint, term: bigint, classId: bigint): Promise<bigint>;
    getOCRExtractionByClass(_classId: bigint): Promise<Array<OCRExtraction>>;
    getOCRExtractionBySubject(_subjectId: bigint): Promise<Array<OCRExtraction>>;
    getOCRExtractionStats(): Promise<bigint>;
    getPublicDashboardData(year: bigint, classId: bigint): Promise<Array<[bigint, bigint]>>;
    getQuestions(questionId: bigint): Promise<Array<Question> | null>;
    getRandomQuestions(questionId: bigint, count: bigint): Promise<Array<Question> | null>;
    getSchoolByExactName(name: string): Promise<School | null>;
    getStudentData(studentPrincipal: Principal): Promise<Student | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisualNotebookChapter(chapterId: bigint): Promise<VisualNotebookChapter | null>;
    getVisualNotebookChapters(): Promise<Array<VisualNotebookChapter>>;
    getVisualNotebookChaptersByExtractedId(extractionId: bigint): Promise<Array<VisualNotebookChapter>>;
    isCallerAdmin(): Promise<boolean>;
    registerStudentWithSchoolName(student: Student, studentPrincipal: Principal, schoolName: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveOCRExtraction(data: OCRExtraction): Promise<void>;
    saveQuestions(question: Question, questionId: bigint): Promise<void>;
    saveVisualNotebookChapter(notebook: VisualNotebookChapter): Promise<void>;
    setVisualNotebookApprovalStatus(chapterId: bigint, status: ApprovalStatus): Promise<void>;
    submitVisualNotebookChapter(id: bigint, title: string, subject: string, classLevel: bigint, flashcards: Array<Flashcard>, slideDeck: SlideDeck, infographics: Array<Infographic>, logicExplanations: Array<LogicExplanation>, uploadedBy: string, contentLanguage: Language, extractionId: bigint, chapterType: ChapterType, approvalStatus: ApprovalStatus): Promise<bigint>;
    updateUserCoinBalance(user: Principal, newBalance: bigint): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, ChapterType as _ChapterType, ExternalBlob as _ExternalBlob, Flashcard as _Flashcard, Infographic as _Infographic, Language as _Language, LogicExplanation as _LogicExplanation, OCRDocumentType as _OCRDocumentType, OCRExtraction as _OCRExtraction, Question as _Question, School as _School, SlideDeck as _SlideDeck, Student as _Student, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VisualNotebookChapter as _VisualNotebookChapter, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addClass(arg0: string, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addClass(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClass(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addSchool(arg0: bigint, arg1: string, arg2: number, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSchool(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSchool(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addSchoolWithExactNameLookup(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSchoolWithExactNameLookup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSchoolWithExactNameLookup(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteOCRData(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOCRData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOCRData(arg0);
            return result;
        }
    }
    async deleteVisualNotebookChapter(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVisualNotebookChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVisualNotebookChapter(arg0);
            return result;
        }
    }
    async getAcademicPerformance(arg0: bigint, arg1: bigint): Promise<Array<[bigint, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAcademicPerformance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAcademicPerformance(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChaptersByClassAndSubject(arg0: bigint, arg1: string): Promise<Array<VisualNotebookChapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChaptersByClassAndSubject(arg0, arg1);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChaptersByClassAndSubject(arg0, arg1);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCumulativeAverage(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCumulativeAverage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCumulativeAverage(arg0, arg1, arg2);
            return result;
        }
    }
    async getOCRExtractionByClass(arg0: bigint): Promise<Array<OCRExtraction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOCRExtractionByClass(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOCRExtractionByClass(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOCRExtractionBySubject(arg0: bigint): Promise<Array<OCRExtraction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOCRExtractionBySubject(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOCRExtractionBySubject(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOCRExtractionStats(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getOCRExtractionStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOCRExtractionStats();
            return result;
        }
    }
    async getPublicDashboardData(arg0: bigint, arg1: bigint): Promise<Array<[bigint, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicDashboardData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicDashboardData(arg0, arg1);
            return result;
        }
    }
    async getQuestions(arg0: bigint): Promise<Array<Question> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestions(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestions(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRandomQuestions(arg0: bigint, arg1: bigint): Promise<Array<Question> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRandomQuestions(arg0, arg1);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRandomQuestions(arg0, arg1);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSchoolByExactName(arg0: string): Promise<School | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchoolByExactName(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchoolByExactName(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentData(arg0: Principal): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentData(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentData(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisualNotebookChapter(arg0: bigint): Promise<VisualNotebookChapter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisualNotebookChapter(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisualNotebookChapter(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisualNotebookChapters(): Promise<Array<VisualNotebookChapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisualNotebookChapters();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisualNotebookChapters();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisualNotebookChaptersByExtractedId(arg0: bigint): Promise<Array<VisualNotebookChapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisualNotebookChaptersByExtractedId(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisualNotebookChaptersByExtractedId(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerStudentWithSchoolName(arg0: Student, arg1: Principal, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudentWithSchoolName(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudentWithSchoolName(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveOCRExtraction(arg0: OCRExtraction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveOCRExtraction(await to_candid_OCRExtraction_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveOCRExtraction(await to_candid_OCRExtraction_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveQuestions(arg0: Question, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveQuestions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveQuestions(arg0, arg1);
            return result;
        }
    }
    async saveVisualNotebookChapter(arg0: VisualNotebookChapter): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVisualNotebookChapter(to_candid_VisualNotebookChapter_n51(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVisualNotebookChapter(to_candid_VisualNotebookChapter_n51(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setVisualNotebookApprovalStatus(arg0: bigint, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setVisualNotebookApprovalStatus(arg0, to_candid_ApprovalStatus_n60(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVisualNotebookApprovalStatus(arg0, to_candid_ApprovalStatus_n60(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitVisualNotebookChapter(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: Array<Flashcard>, arg5: SlideDeck, arg6: Array<Infographic>, arg7: Array<LogicExplanation>, arg8: string, arg9: Language, arg10: bigint, arg11: ChapterType, arg12: ApprovalStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitVisualNotebookChapter(arg0, arg1, arg2, arg3, to_candid_vec_n62(this._uploadFile, this._downloadFile, arg4), to_candid_SlideDeck_n58(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_vec_n53(this._uploadFile, this._downloadFile, arg7), arg8, to_candid_Language_n56(this._uploadFile, this._downloadFile, arg9), arg10, to_candid_ChapterType_n65(this._uploadFile, this._downloadFile, arg11), to_candid_ApprovalStatus_n60(this._uploadFile, this._downloadFile, arg12));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitVisualNotebookChapter(arg0, arg1, arg2, arg3, to_candid_vec_n62(this._uploadFile, this._downloadFile, arg4), to_candid_SlideDeck_n58(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_vec_n53(this._uploadFile, this._downloadFile, arg7), arg8, to_candid_Language_n56(this._uploadFile, this._downloadFile, arg9), arg10, to_candid_ChapterType_n65(this._uploadFile, this._downloadFile, arg11), to_candid_ApprovalStatus_n60(this._uploadFile, this._downloadFile, arg12));
            return result;
        }
    }
    async updateUserCoinBalance(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserCoinBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserCoinBalance(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ChapterType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChapterType): ChapterType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Flashcard_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Flashcard): Flashcard {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_LogicExplanation_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LogicExplanation): LogicExplanation {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_OCRDocumentType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OCRDocumentType): OCRDocumentType {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
async function from_candid_OCRExtraction_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OCRExtraction): Promise<OCRExtraction> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_SlideDeck_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SlideDeck): SlideDeck {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_VisualNotebookChapter_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisualNotebookChapter): VisualNotebookChapter {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Question>]): Array<Question> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_School]): School | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VisualNotebookChapter]): VisualNotebookChapter | null {
    return value.length === 0 ? null : from_candid_VisualNotebookChapter_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coinBalance: bigint;
    name: string;
    role: string;
    classId: [] | [bigint];
    schoolId: [] | [bigint];
}): {
    coinBalance: bigint;
    name: string;
    role: string;
    classId?: bigint;
    schoolId?: bigint;
} {
    return {
        coinBalance: value.coinBalance,
        name: value.name,
        role: value.role,
        classId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.classId)),
        schoolId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.schoolId))
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    logicExplanations: Array<_LogicExplanation>;
    title: string;
    subject: string;
    contentLanguage: _Language;
    slideDeck: _SlideDeck;
    extractionId: bigint;
    approvalStatus: _ApprovalStatus;
    infographics: Array<_Infographic>;
    creationTime: _Time;
    classLevel: bigint;
    flashcards: Array<_Flashcard>;
    uploadedBy: string;
    chapterType: _ChapterType;
}): {
    id: bigint;
    logicExplanations: Array<LogicExplanation>;
    title: string;
    subject: string;
    contentLanguage: Language;
    slideDeck: SlideDeck;
    extractionId: bigint;
    approvalStatus: ApprovalStatus;
    infographics: Array<Infographic>;
    creationTime: Time;
    classLevel: bigint;
    flashcards: Array<Flashcard>;
    uploadedBy: string;
    chapterType: ChapterType;
} {
    return {
        id: value.id,
        logicExplanations: from_candid_vec_n18(_uploadFile, _downloadFile, value.logicExplanations),
        title: value.title,
        subject: value.subject,
        contentLanguage: from_candid_Language_n21(_uploadFile, _downloadFile, value.contentLanguage),
        slideDeck: from_candid_SlideDeck_n23(_uploadFile, _downloadFile, value.slideDeck),
        extractionId: value.extractionId,
        approvalStatus: from_candid_ApprovalStatus_n25(_uploadFile, _downloadFile, value.approvalStatus),
        infographics: value.infographics,
        creationTime: value.creationTime,
        classLevel: value.classLevel,
        flashcards: from_candid_vec_n27(_uploadFile, _downloadFile, value.flashcards),
        uploadedBy: value.uploadedBy,
        chapterType: from_candid_ChapterType_n31(_uploadFile, _downloadFile, value.chapterType)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    concept: string;
    language: _Language;
    whyInsights: string;
    stepByStepExplanation: string;
}): {
    id: bigint;
    concept: string;
    language: Language;
    whyInsights: string;
    stepByStepExplanation: string;
} {
    return {
        id: value.id,
        concept: value.concept,
        language: from_candid_Language_n21(_uploadFile, _downloadFile, value.language),
        whyInsights: value.whyInsights,
        stepByStepExplanation: value.stepByStepExplanation
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    subject: string;
    slides: Array<string>;
    language: _Language;
    summary: string;
    classLevel: bigint;
}): {
    id: bigint;
    title: string;
    subject: string;
    slides: Array<string>;
    language: Language;
    summary: string;
    classLevel: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        subject: value.subject,
        slides: value.slides,
        language: from_candid_Language_n21(_uploadFile, _downloadFile, value.language),
        summary: value.summary,
        classLevel: value.classLevel
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    front: string;
    exampleSentence: string;
    back: string;
    imageUrl: [] | [string];
}): {
    id: bigint;
    front: string;
    exampleSentence: string;
    back: string;
    imageUrl?: string;
} {
    return {
        id: value.id,
        front: value.front,
        exampleSentence: value.exampleSentence,
        back: value.back,
        imageUrl: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.imageUrl))
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    _id: bigint;
    documentType: _OCRDocumentType;
    _percentage_textbook: number;
    content: string;
    _textbook_parts: bigint;
    validationResults: string;
    fileName: string;
    _total_text_parts: bigint;
    classId: bigint;
    schoolId: bigint;
    subjectId: bigint;
    relevance: string;
    pdfId: [] | [_ExternalBlob];
    uploadTime: _Time;
    _extracted_Questions: string;
}): Promise<{
    _id: bigint;
    documentType: OCRDocumentType;
    _percentage_textbook: number;
    content: string;
    _textbook_parts: bigint;
    validationResults: string;
    fileName: string;
    _total_text_parts: bigint;
    classId: bigint;
    schoolId: bigint;
    subjectId: bigint;
    relevance: string;
    pdfId?: ExternalBlob;
    uploadTime: Time;
    _extracted_Questions: string;
}> {
    return {
        _id: value._id,
        documentType: from_candid_OCRDocumentType_n36(_uploadFile, _downloadFile, value.documentType),
        _percentage_textbook: value._percentage_textbook,
        content: value.content,
        _textbook_parts: value._textbook_parts,
        validationResults: value.validationResults,
        fileName: value.fileName,
        _total_text_parts: value._total_text_parts,
        classId: value.classId,
        schoolId: value.schoolId,
        subjectId: value.subjectId,
        relevance: value.relevance,
        pdfId: record_opt_to_undefined(await from_candid_opt_n38(_uploadFile, _downloadFile, value.pdfId)),
        uploadTime: value.uploadTime,
        _extracted_Questions: value._extracted_Questions
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hindi: null;
} | {
    hinglish: null;
} | {
    english: null;
}): Language {
    return "hindi" in value ? Language.hindi : "hinglish" in value ? Language.hinglish : "english" in value ? Language.english : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    math: null;
} | {
    science: null;
}): ChapterType {
    return "math" in value ? ChapterType.math : "science" in value ? ChapterType.science : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignment: null;
} | {
    textbook: null;
} | {
    worksheet: null;
}): OCRDocumentType {
    return "assignment" in value ? OCRDocumentType.assignment : "textbook" in value ? OCRDocumentType.textbook : "worksheet" in value ? OCRDocumentType.worksheet : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VisualNotebookChapter>): Array<VisualNotebookChapter> {
    return value.map((x)=>from_candid_VisualNotebookChapter_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LogicExplanation>): Array<LogicExplanation> {
    return value.map((x)=>from_candid_LogicExplanation_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Flashcard>): Array<Flashcard> {
    return value.map((x)=>from_candid_Flashcard_n28(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OCRExtraction>): Promise<Array<OCRExtraction>> {
    return await Promise.all(value.map(async (x)=>await from_candid_OCRExtraction_n34(_uploadFile, _downloadFile, x)));
}
function to_candid_ApprovalStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid_ChapterType_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChapterType): _ChapterType {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Flashcard_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Flashcard): _Flashcard {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_Language_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_LogicExplanation_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LogicExplanation): _LogicExplanation {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_OCRDocumentType_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OCRDocumentType): _OCRDocumentType {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
async function to_candid_OCRExtraction_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OCRExtraction): Promise<_OCRExtraction> {
    return await to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_SlideDeck_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SlideDeck): _SlideDeck {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_VisualNotebookChapter_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisualNotebookChapter): _VisualNotebookChapter {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coinBalance: bigint;
    name: string;
    role: string;
    classId?: bigint;
    schoolId?: bigint;
}): {
    coinBalance: bigint;
    name: string;
    role: string;
    classId: [] | [bigint];
    schoolId: [] | [bigint];
} {
    return {
        coinBalance: value.coinBalance,
        name: value.name,
        role: value.role,
        classId: value.classId ? candid_some(value.classId) : candid_none(),
        schoolId: value.schoolId ? candid_some(value.schoolId) : candid_none()
    };
}
async function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    _id: bigint;
    documentType: OCRDocumentType;
    _percentage_textbook: number;
    content: string;
    _textbook_parts: bigint;
    validationResults: string;
    fileName: string;
    _total_text_parts: bigint;
    classId: bigint;
    schoolId: bigint;
    subjectId: bigint;
    relevance: string;
    pdfId?: ExternalBlob;
    uploadTime: Time;
    _extracted_Questions: string;
}): Promise<{
    _id: bigint;
    documentType: _OCRDocumentType;
    _percentage_textbook: number;
    content: string;
    _textbook_parts: bigint;
    validationResults: string;
    fileName: string;
    _total_text_parts: bigint;
    classId: bigint;
    schoolId: bigint;
    subjectId: bigint;
    relevance: string;
    pdfId: [] | [_ExternalBlob];
    uploadTime: _Time;
    _extracted_Questions: string;
}> {
    return {
        _id: value._id,
        documentType: to_candid_OCRDocumentType_n48(_uploadFile, _downloadFile, value.documentType),
        _percentage_textbook: value._percentage_textbook,
        content: value.content,
        _textbook_parts: value._textbook_parts,
        validationResults: value.validationResults,
        fileName: value.fileName,
        _total_text_parts: value._total_text_parts,
        classId: value.classId,
        schoolId: value.schoolId,
        subjectId: value.subjectId,
        relevance: value.relevance,
        pdfId: value.pdfId ? candid_some(await to_candid_ExternalBlob_n50(_uploadFile, _downloadFile, value.pdfId)) : candid_none(),
        uploadTime: value.uploadTime,
        _extracted_Questions: value._extracted_Questions
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    logicExplanations: Array<LogicExplanation>;
    title: string;
    subject: string;
    contentLanguage: Language;
    slideDeck: SlideDeck;
    extractionId: bigint;
    approvalStatus: ApprovalStatus;
    infographics: Array<Infographic>;
    creationTime: Time;
    classLevel: bigint;
    flashcards: Array<Flashcard>;
    uploadedBy: string;
    chapterType: ChapterType;
}): {
    id: bigint;
    logicExplanations: Array<_LogicExplanation>;
    title: string;
    subject: string;
    contentLanguage: _Language;
    slideDeck: _SlideDeck;
    extractionId: bigint;
    approvalStatus: _ApprovalStatus;
    infographics: Array<_Infographic>;
    creationTime: _Time;
    classLevel: bigint;
    flashcards: Array<_Flashcard>;
    uploadedBy: string;
    chapterType: _ChapterType;
} {
    return {
        id: value.id,
        logicExplanations: to_candid_vec_n53(_uploadFile, _downloadFile, value.logicExplanations),
        title: value.title,
        subject: value.subject,
        contentLanguage: to_candid_Language_n56(_uploadFile, _downloadFile, value.contentLanguage),
        slideDeck: to_candid_SlideDeck_n58(_uploadFile, _downloadFile, value.slideDeck),
        extractionId: value.extractionId,
        approvalStatus: to_candid_ApprovalStatus_n60(_uploadFile, _downloadFile, value.approvalStatus),
        infographics: value.infographics,
        creationTime: value.creationTime,
        classLevel: value.classLevel,
        flashcards: to_candid_vec_n62(_uploadFile, _downloadFile, value.flashcards),
        uploadedBy: value.uploadedBy,
        chapterType: to_candid_ChapterType_n65(_uploadFile, _downloadFile, value.chapterType)
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    concept: string;
    language: Language;
    whyInsights: string;
    stepByStepExplanation: string;
}): {
    id: bigint;
    concept: string;
    language: _Language;
    whyInsights: string;
    stepByStepExplanation: string;
} {
    return {
        id: value.id,
        concept: value.concept,
        language: to_candid_Language_n56(_uploadFile, _downloadFile, value.language),
        whyInsights: value.whyInsights,
        stepByStepExplanation: value.stepByStepExplanation
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    subject: string;
    slides: Array<string>;
    language: Language;
    summary: string;
    classLevel: bigint;
}): {
    id: bigint;
    title: string;
    subject: string;
    slides: Array<string>;
    language: _Language;
    summary: string;
    classLevel: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        subject: value.subject,
        slides: value.slides,
        language: to_candid_Language_n56(_uploadFile, _downloadFile, value.language),
        summary: value.summary,
        classLevel: value.classLevel
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    front: string;
    exampleSentence: string;
    back: string;
    imageUrl?: string;
}): {
    id: bigint;
    front: string;
    exampleSentence: string;
    back: string;
    imageUrl: [] | [string];
} {
    return {
        id: value.id,
        front: value.front,
        exampleSentence: value.exampleSentence,
        back: value.back,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none()
    };
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OCRDocumentType): {
    assignment: null;
} | {
    textbook: null;
} | {
    worksheet: null;
} {
    return value == OCRDocumentType.assignment ? {
        assignment: null
    } : value == OCRDocumentType.textbook ? {
        textbook: null
    } : value == OCRDocumentType.worksheet ? {
        worksheet: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    hindi: null;
} | {
    hinglish: null;
} | {
    english: null;
} {
    return value == Language.hindi ? {
        hindi: null
    } : value == Language.hinglish ? {
        hinglish: null
    } : value == Language.english ? {
        english: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChapterType): {
    math: null;
} | {
    science: null;
} {
    return value == ChapterType.math ? {
        math: null
    } : value == ChapterType.science ? {
        science: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<LogicExplanation>): Array<_LogicExplanation> {
    return value.map((x)=>to_candid_LogicExplanation_n54(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Flashcard>): Array<_Flashcard> {
    return value.map((x)=>to_candid_Flashcard_n63(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
